sqs:
  local:
    params:
      region: sqs
      endpoint: http://sqs:9324
      apiVersion: "2012-11-05"
    queueName:
      - cvs-update-store-queue
  remote:
    params:
      apiVersion: "2012-11-05"
    queueName:
      - cvs-update-store-${BRANCH}-queue
s3:
  local:
    params:
      endpoint: http://s3:9324
      bucket: cvs-sqs-queues-${BRANCH}
  remote:
    params:
      endpoint: https://s3.${AWS_REGION}.amazonaws.com
      bucket: cvs-sqs-queues-${BRANCH}

targets:
  test-results:
    queue: cvs-update-store-${BRANCH}-queue
    dlQueue: cvs-update-store-${BRANCH}-dlq
    swaggerSpecFile: API_Vehicle_Test_Results_CVS_EDH_v1.yaml
    schemaItem: completeTestResults
  activities:
    queue: cvs-update-store-${BRANCH}-queue
    dlQueue: cvs-update-store-${BRANCH}-dlq
    swaggerSpecFile: API_Activities_CVS_EDH_v1.yaml
    schemaItem: activity
  technical_records:
    queue: cvs-update-store-${BRANCH}-queue
    dlQueue: cvs-update-store-${BRANCH}-dlq
    swaggerSpecFile: API_Vehicle_Tech_Records_CVS_EDH_v1.yaml
    schemaItem: completeTechRecordDB
